export const RESET_BOARD = "RESET_BOARD";
export const SET_DIFFICULTY = "SET_DIFFICULTY";
export const START_FETCHING_BOARD = "START_FETCHING_BOARD";
export const DONE_FETCHING_BOARD = "DONE_FETCHING_BOARD";
export const INITIALIZE_BOARD = "INITIALIZE_BOARD";
export const SET_CURRENT_CELL = "SET_CURRENT_CELL";
export const SET_NUMBER = "SET_NUMBER";
export const CLEAR_BOARD = "CLEAR_BOARD";
export const TOGGLE_WRITE_CANDIDATES = "TOGGLE_WRITE_CANDIDATES";
export const TOGGLE_CANDIDATE = "TOGGLE_CANDIDATE";
export const SET_SOLUTION = "SET_SOLUTION";
export const TOGGLE_SHOW_HELP = "TOGGLE_SHOW_HELP";
export const ADD_HELP_USAGE = "ADD_HELP_USAGE";
export const ADD_HINT = "ADD_HINT";
export const TOGGLE_ON_THE_GO_VALIDATION = "TOGGLE_ON_THE_GO_VALIDATION";
export const TOGGLE_SHOW_CONNECTED_CELLS = "TOGGLE_SHOW_CONNECTED_CELLS";
export const TOGGLE_PLACE_ALL_OF_ACTIVE = "TOGGLE_PLACE_ALL_OF_ACTIVE";
export const SET_INVALID_CELLS = "SET_INVALID_CELLS";
export const REMOVE_CELL_FROM_INVALID = "REMOVE_CELL_FROM_INVALID";
export const PLACE_ALL_OF = "PLACE_ALL_OF";
export const VALIDATE_SUDOKU = "VALIDATE_SUDOKU";

export const HELP_TYPE_HINT = 'hint', HELP_TYPE_VALIDATION = 'validation',
             HELP_TYPE_PLACE_ALL_OF = 'placeAllOf', HELP_TYPE_ON_THE_GO_VALIDATION = 'onTheGoValidation';

