export const RESET_STATE = "RESET_STATE";
export const SET_LOADING = "SET_LOADING";
export const SET_BOARD = "SET_BOARD";
export const SET_INITIALIZED = "SET_INITIALIZED";
export const SET_DIFFICULTY = "SET_DIFFICULTY";
export const SET_CURRENT_CELL = "SET_CURRENT_CELL";
export const SET_WRITE_CANDIDATES = "SET_WRITE_CANDIDATES";
export const SET_CANDIDATES = "SET_CANDIDATES";
export const SET_SOLUTION = "SET_SOLUTION";
export const SET_INVALID_CELLS = "SET_INVALID_CELLS";
export const SET_SHOW_HELP = "SET_SHOW_HELP";
export const SET_HELP_USAGE = "SET_HELP_USAGE";
export const SET_ON_THE_GO_VALIDATION = "SET_ON_THE_GO_VALIDATION";
export const SET_SHOW_CONNECTED_CELLS = "SET_SHOW_CONNECTED_CELLS";
export const SET_PLACE_ALL_OF_ACTIVE = "SET_PLACE_ALL_OF_ACTIVE";
export const SET_TIMER_ACTIVE = "SET_TIMER_ACTIVE";
export const SET_TIME_ELAPSED = "SET_TIME_ELAPSED";


export const HELP_TYPE_HINT = 'hint', HELP_TYPE_VALIDATION = 'validation',
             HELP_TYPE_PLACE_ALL_OF = 'placeAllOf', HELP_TYPE_ON_THE_GO_VALIDATION = 'onTheGoValidation';

