
export const RESET_HELP_STATE = "RESET_HELP_STATE";
export const SET_SOLUTION = "SET_SOLUTION";
export const SET_INVALID_CELLS = "SET_INVALID_CELLS";
export const SET_SHOW_HELP = "SET_SHOW_HELP";
export const SET_HELP_USAGE = "SET_HELP_USAGE";
export const SET_ON_THE_GO_VALIDATION = "SET_ON_THE_GO_VALIDATION";
export const SET_SHOW_CONNECTED_CELLS = "SET_SHOW_CONNECTED_CELLS";
export const SET_PLACE_ALL_OF_ACTIVE = "SET_PLACE_ALL_OF_ACTIVE";
export const SET_HINTED_CELLS = "SET_HINTED_CELLS";
